# List of words to match in the filenames
words_to_match = [
    '2B', 'A2', 'Abigail', 'Ada', 'Aeris', 'Aerith', 'Agatha', 'Aisha', 'Aislinn', 'Akali',
    'Albedo', 'Alejandra', 'Alessa', 'Alex', 'Alexia', 'Alexstrasza', 'Alice', 'Alicia', 'Alina', 'Aline',
    'Allison', 'Alma', 'Alois', 'Aloy', 'Althea', 'Alya', 'Alyssa', 'Alyx', 'Amalia', 'Amanda',
    'Amaterasu', 'Amber', 'Amelie', 'Amira', 'Amy', 'Ana', 'Anastasia', 'Anaïs', 'Andromeda', 'Angela',
    'Angelica', 'Angie', 'Anita', 'Ann', 'Anna', 'Annabelle', 'Anne', 'Annette', 'Annie', 'Anthea',
    'Antonia', 'Anya', 'April', 'Aqua', 'Araceli', 'Aran', 'Aranea', 'Aria', 'Ariel', 'Arwen',
    'Ashley', 'Ashlyn', 'Athena', 'Aurora', 'Ava', 'Aveline', 'Avery', 'Avril', 'Axelle', 'Ayaka',
    'Ayane', 'Ayumi', 'Azami', 'Azura', 'Barbara', 'Bayonetta', 'bayo','Beatrice', 'Beatrix', 'Bella', 'Belle',
    'Bernadette', 'Beth', 'Betsy', 'Betty', 'Bianca', 'Blair', 'Blanche', 'Bonnie', 'Brenda', 'Brenna',
    'Bridget', 'Brigitte', 'Britney', 'Brooke', 'Caitlin', 'Caleigh', 'Callie', 'Camila', 'Camille', 'Cammy',
    'Candace', 'Caren', 'Carina', 'Carla', 'Carmen', 'Carol', 'Caroline', 'Carrie', 'Cassandra', 'Cassie',
    'Catalina', 'Cate', 'Catherine', 'Cathy', 'Cecilia', 'Celes', 'Celeste', 'Celia', 'Cerise', 'Chantal',
    'Charlene', 'Charlie', 'Charlotte', 'Chell', 'Chelsea', 'Cheryl', 'Chloe', 'Christina', 'Christine', 'Chromie',
    'Chun-Li', 'Cindy', 'Ciri','Cirilla', 'Claire', 'Clementine', 'Cortana', 'D.Va', 'Daisy', 'Edea', 'Eiko',
    'Elena', 'Elizabeth', 'Ellie', 'Emily', 'Erendira', 'Faith', 'Fang', 'Fiona', 'Fran', 'Freya',
    'GLaDOS', 'Gaige', 'Garnet', 'Helena', 'Iris', 'Ivy', 'Jade', 'Jaina', 'Jessie', 'Jill',
    'Joanna', 'Jodie', 'KOS-MOS', 'Kairi', 'Kassandra', 'Kasumi', 'Kat', 'Kerrigan', 'Kinzie', 'Kitana',
    'Lara', 'Larxene', 'Li Li', 'Lightning', 'Lili', 'Lillith', 'Ling', 'Lulu', 'Lunafreya', 'Madison',
    'Maeve', 'Maiev', 'Maya', 'Meryl', 'Miranda', 'Moira', 'Mona', 'Morrigan', 'Nadine', 'Namine',
    'Nariko', 'Nilin', 'Nina', 'Noel', 'Nova', 'Olette', 'Orianna', 'Paige', 'Paine', 'Patricia',
    'Peach', 'Quiet', 'Quistis', 'Rayne', 'Rebecca', 'Regina', 'Rikku', 'Riley', 'Rinoa', 'River',
    'Rosalina', 'Rosalind', 'Rose', 'Samus', 'Sarah', 'Selphie', 'Senua', 'Serah', 'Serana', 'Shanoa',
    'Shantae', 'Shaundi', 'Sherry', 'Sheva', 'Shion', 'Shodan', 'Sindel', 'Sombra', 'Sonya', 'Sophitia',
    'Sully', 'Sylvanas', 'Taki', 'Tali', 'Talim', 'Tanya', 'Tatsumaki', 'Terra', 'Thalia', 'Thea',
    'Tifa', 'Tracer', 'Triss', 'Tyrande', 'Ulala', 'Ultimecia', 'Valeera', 'Vanille', 'Vella', 'Vi',
    'Vivi', 'Whitemane', 'Xion', 'Yennefer', 'Yen', 'Yenn', 'Yuffie', 'Yuna', 'Zarya', 'Zelda', 'Zoe', 'Zula',
    'Saber', 'Pharah', 'Mercy', 'Hitomi', 'Phanam', 'Mikasa', 'Juri', 'Boa', 'Mitsuki', 'BlackCat', 'Nami', 'Supergirl'
]